### ISSUE TITLE
About install crash

### ISSUE THREAD

**Issue by a7884594** [MythicManiac/MythicModManager#11]
If the network is not good, click install will crash...

**Comment by a7884594** [comment]
Downloading AsterAether-AetherLib-0.2.0
Traceback (most recent call last):
  File "site-packages\urllib3\connection.py", line 159, in _new_conn
  File "site-packages\urllib3\util\connection.py", line 80, in create_connection
  File "site-packages\urllib3\util\connection.py", line 70, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 600, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 343, in _make_request
  File "site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
  File "site-packages\urllib3\connection.py", line 301, in connect
  File "site-packages\urllib3\connection.py", line 168, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000002759A665EF0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 638, in urlopen
  File "site-packages\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /thunderstore/live/AsterAether-AetherLib-0.2.0.zip (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002759A665EF0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间 后没有正确答复或连接的主机没有反应，连接尝试失败。',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manager\main.py", line 485, in <module>
  File "manager\main.py", line 481, in main
  File "manager\main.py", line 476, in launch
  File "manager\main.py", line 415, in update
  File "manager\main.py", line 368, in install_mod
  File "manager\main.py", line 207, in download_and_install
  File "manager\main.py", line 87, in download_mod
  File "site-packages\requests\api.py", line 75, in get
  File "site-packages\requests\api.py", line 60, in request
  File "site-packages\requests\sessions.py", line 533, in request
  File "site-packages\requests\sessions.py", line 668, in send
  File "site-packages\requests\sessions.py", line 668, in <listcomp>
  File "site-packages\requests\sessions.py", line 247, in resolve_redirects
  File "site-packages\requests\sessions.py", line 646, in send
  File "site-packages\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /thunderstore/live/AsterAether-AetherLib-0.2.0.zip (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002759A665EF0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[23396] Failed to execute script main
PS F:\SteamLibrary\steamapps\common\Risk of Rain 2\MythicManiac-MythicModManager-1.0.1> MythicModManagerMythicModManager

**Comment by Sipondo** [comment]
This currently is expected behaviour, as the manager acts as a download manager.
We will make sure to include offline support for newer iterations.
